/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)  {
        System.out.println(new App().getGreeting());
        Graph<String> graph = new Graph();
        System.out.println(graph.addNode("A"));
        System.out.println(graph.addNode("B"));
        System.out.println( graph.addNode("C"));


    graph.addEdge("A", "B",1);
    graph.addEdge("A", "C",3);
    graph.addEdge("c", "B",2);

    System.out.println(graph.toString());
    System.out.println(graph.size());
    System.out.println(graph.getNeighbors("A"));//B ,C
    System.out.println(graph.getNodes());// [A, B, C]

    }
}
