/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)  {
        System.out.println(new App().getGreeting());
        Graph<String> graph = new Graph();


        System.out.println(graph.addNode("A"));
        System.out.println(graph.addNode("B"));
        System.out.println( graph.addNode("C"));
        Graph<String> graph1 = new Graph();
        graph1.addNode("Pandora");
        graph1.addNode("Arendelle");
        graph1.addNode("Metroville");
        graph1.addNode("Monstroplolis");
        graph1.addNode("Narnia");
        graph1.addNode("Naboo");

        graph1.addEdge("Pandora", "Arendelle",150);
        graph1.addEdge("Metroville", "Pandora",82);
        graph1.addEdge("Metroville", "Arendelle",99);
        graph1.addEdge("Arendelle", "Monstroplolis",42);
        graph1.addEdge("Monstroplolis", "Naboo",73);
        graph1.addEdge("Metroville", "Monstroplolis",105);
        graph1.addEdge("Metroville", "Narnia",37);
        graph1.addEdge("Metroville", "Naboo",26);
        graph1.addEdge("Naboo", "Narnia",250);

    graph.addEdge("A", "B",1);
    graph.addEdge("A", "C",3);
    graph.addEdge("c", "B",2);

    System.out.println(graph.toString());
    System.out.println(graph.size());
    System.out.println(graph.getNeighbors("A"));//B ,C
    System.out.println(graph.getNodes());// [A, B, C]
    System.out.println( graph1.BreadthFirst("Metroville"));//Pandora, Arendelle, Metroville, Monstroplolis, Narnia, Naboo
        //[Arendelle, New Monstroplolis, Naboo]	True, $115
        ArrayList<String > cityNames = new ArrayList<>();
        cityNames.add("Arendelle");
        cityNames.add("Monstroplolis");
        cityNames.add("Naboo");
        System.out.println(cityNames);
        System.out.println(graph1.businessTrip(graph1,cityNames));
        System.out.println("-------------------------------------------");
        Graph<String> graph2 = new Graph();
        graph2.addNode("A");
        graph2.addNode("B");
        graph2.addNode("H");
        graph2.addNode("C");
        graph2.addNode("D");
        graph2.addNode("E");
        graph2.addNode("F");

        graph2.addEdge("A", "B",1);
        graph2.addEdge("B", "D",3);
        graph2.addEdge("B", "C",2);
        graph2.addEdge("C", "G",0);
        graph2.addEdge("D", "E",2);
        graph2.addEdge("D", "H",2);
        graph2.addEdge("D", "F",2);
        graph2.addEdge("H", "F",2);


        System.out.println(graph2.depthFirst("A"));
//A, B, C, G, D, E, H, F
    }
}
