/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void TestMergesort() {
        App app = new App();
        int [] arr = {20,18,12,8,5,-2};

    assertEquals("[-2, 5, 8, 12, 18, 20]",Arrays.toString(app.Mergesort(arr)));
    }
    @Test void TestMergesortEmptyArray() {
        App app = new App();
        int [] arr = {};

        assertEquals("[]",Arrays.toString(app.Mergesort(arr)));
    }
}
