/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void TestInsertionSort() {
        App app = new App();
        int[] arr = {8, 4, 23, 42, 16, 15};
        assertEquals("[4, 8, 15, 16, 23, 42]",Arrays.toString(app.insertionSort(arr)));
    }
    @Test void TestInsertionSortOneEle() {
        App app = new App();
        int[] arr = {8};
        assertEquals("[8]",Arrays.toString(app.insertionSort(arr)));
    }
    @Test void TestInsertionSortForEmptyArray() {
        App app = new App();
        int[] arr = {};
        assertEquals("[]",Arrays.toString(app.insertionSort(arr)));
    }

}
