/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        HashTable<String,Integer> hashTable=new HashTable<>();
        hashTable.add("8",2);
        BinarySearchTree<Integer> tree = new BinarySearchTree<>();
        tree.add(150);
        tree.add(100);
        tree.add(200);
        tree.add(250);
        tree.add(75);
        tree.add(125);
        tree.add(175);
        tree.add(300);
        tree.add(160);
        tree.add(350);
        BinarySearchTree<Integer> tree2 = new BinarySearchTree<>();
        tree2.add(42);
        tree2.add(15);
        tree2.add(100);
        tree2.add(200);
        tree2.add(500);
        tree2.add(600);
        tree2.add(125);
        tree2.add(160);
        tree2.add(175);
        tree2.add(350);

        System.out.println(tree.inOrder(tree.root));
        System.out.println(tree.inOrder(tree2.root));
        System.out.println(hashTable.tree_intersection(tree,tree2));

    }
}
