/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
          int [] arr = {8,4,23,42,16,15};
//        int [] arr = {20,18,12,8,5,-2};
        int n = arr.length;
        System.out.println(Arrays.toString(QuickSort(arr,0,n-1))); // [-2, 5, 8, 12, 18, 20]
    }//main

        public static int[] QuickSort ( int[] arr, int left, int right){
        if(left < right){
            int position = partition(arr, left, right);
            QuickSort(arr, left, position - 1);
            QuickSort(arr, position + 1, right);
        }
            return arr;
        }//QuickSort

    static int partition(int[] arr, int left, int right) {

        int pivot = arr[right];

        int low = (left - 1);

        for (int i = left; i <= right - 1; i++) {
            if (arr[i] < pivot) {

                low++;
                swap(arr, low, i);
            }
        }
        swap(arr, low + 1, right);
        return (low + 1);
    }
    static void swap(int[] arr, int i, int low) {
        int temp;
        temp = arr[i];
        arr[i] = arr[low];
        arr[low] = temp;
    }

}//app
