/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        HashTable<String,String> hashTable = new HashTable<>();
        hashTable.add("FirstName","Dima");
        hashTable.add("LastName","Zeklam");
        System.out.println(hashTable.get("FirstName"));
        System.out.println(hashTable.contains("age"));
        System.out.println(hashTable.hash("LastName"));


    }


}
