/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import trees.KaryTree.KaryTree;

public class App {

    public static void main(String[] args) {
 BinarySearchTree<Integer>tree = new BinarySearchTree<>();
        tree.add(10);
        tree.add(5);
        tree.add(30);
        tree.add(7);
        tree.add(9);
        tree.add(11);
        System.out.println(tree.root);
        System.out.println(tree.contains(10));
        System.out.println(tree.preOrder(tree.root));
        System.out.println(tree.inOrder(tree.root));
        System.out.println(tree.postOrder(tree.root));
        System.out.println("The max number in the tree is: " + tree.treeMax());
        System.out.println(tree.breadthFirst(tree));
        System.out.println("-----------------------------------------");
        KaryTree<Integer> karyTree = new KaryTree<Integer>(3);
        karyTree.add(9);
        karyTree.add(30);
        karyTree.add(3);
        karyTree.add(5);
        karyTree.add(15);
        karyTree.add(6);
        karyTree.add(2);
        System.out.println(karyTree.toString());
        System.out.println(karyTree.fizzBuzzTree(karyTree));

    }
}
