/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hash_table;

import java.util.ArrayList;
import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        HashTable<String, String> Hash1 = new HashTable<>();
        HashTable<String, String> Hash2 = new HashTable<>();
        Hash1.add("fond", "enamored");
        Hash1.add("wrath", "anger");
        Hash1.add("diligent", "employed");
        Hash1.add("outfit", "garb");
        Hash1.add("guide", "usher");

        Hash2.add("fond", "averse");
        Hash2.add("wrath", "delight");
        Hash2.add("diligent", "idle");
        Hash2.add("guide", "follow");
        Hash2.add("flow", "jam");
        ArrayList<ArrayList<String>> list =Hash1.leftJoin(Hash1,Hash2);
        HashTable<Character, Integer> Hashtable = new HashTable<>();
        System.out.println(list);
        String str = "The quick brown fox jumps over the lazy dog";
        String str2 = "I love catsi";
        String s="";
        System.out.println(Hashtable.isUnique(str2));
        System.out.println(Hashtable.repeatedWord("No. Try not. Do or do not. There is no try."));
    }
}
