/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();
    @Test void TestPushOntoStack() {

        Stack<Integer> stack = new Stack<>();
        stack.push(8);
String test = "8";
assertEquals(test,stack.peek());
    }
}
