/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;

public class App {

    public static void main(String[] args) {


        Stack<Integer> stack = new Stack<>();
        System.out.println(stack.isEmpty());
        stack.push(1);
        stack.push(2);
        stack.push(3);
        System.out.println(stack.isEmpty());
        System.out.println(stack.peek());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.toString());
//        stack.push(10);
//        stack.push(30);
//        stack.push(45);
        System.out.println(stack.toString());
        Queue<Integer> queue = new Queue<>();
        queue.enqueue(3);
        System.out.println(queue.isEmpty());
        queue.enqueue(7);
        System.out.println(queue.isEmpty());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        queue.enqueue(11);
        System.out.println(queue.peek());
//        System.out.println(stack.peek());
//        System.out.println(stack.pop());

    }
}
